name: Check Retracted Articles in .bib Files

on:
  push:
    paths:
      - '**/*.bib'
  pull_request:
    paths:
      - '**/*.bib'
  workflow_dispatch:

jobs:
  check-retractions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "bibtexparser==1.4.0" > requirements.txt
          echo "pandas==2.0.3" >> requirements.txt
          echo "requests==2.31.0" >> requirements.txt
          echo "PyGithub==1.59.1" >> requirements.txt
          pip install -r requirements.txt
          pip list
          python -c "import sys; print(sys.path)"
          
      - name: Check Installed Packages
        run: pip list  # Debugging step to confirm installation

      - name: Run Retraction Check
        run: python .github/scripts/check_retractions.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
